### PR TITLE
fixed issue #446 (no semicolons after Update/Create statements in Postgres)

### PR DESCRIPTION
**Pull request by wolfascu**
I have modified `PostgresGenerator` and `PostgresDescriptionGenerator` to issue semicolons after every statement.

### CODE REVIEW

**Comment by tommarien** [comment]
@clupascu Can you adapt tests also ?

**Comment by clupascu** [comment]
Oops. Right! I will undo my changes to `GenericGenerator` and will implement them in the specialized `PostgresGenerator`.

**Comment by clupascu** [comment]
@tommarien I pushed a new commit that only affects the `PostgresGenerator` and all tests pass now.

**Comment by coldacid** [comment]
Since issue #446 is marked vNext, could we get this PR landed?

**Comment by tommarien** [comment]
@wolfascu Thanks for this patch

**Comment by wolfascu** [comment]
@tommarien Thank you for merging! (And sorry for my initial mistake!)

**Comment by coldacid** [comment]
Thanks @wolfascu for the fix and @tommarien for getting 1.6.1 out right after the merge! You guys saved our bacon with this.

**Pull request merged**
