### PR TITLE
Improvements for PostgreSql provider

### PR DESCRIPTION
**Pull request by stsrki**
1. Added ability to set default value for uuid column to generate
sequential uuids.
2. Fixed generation of column/table description by adding quoter to the
generator.

### CODE REVIEW

**Comment by tommarien** [comment]
@stsrki looks good, is uuid_generate_v1() a true alternative for sql's SequentialId ?

**Comment by stsrki** [comment]
Well it seems to be sequential. I tested it by populating my test table and it works as expected when sorting.

Quick google search: http://labria.github.io/2013/04/28/rails-4-postgres-uuid-pk-guide/

**Comment by tommarien** [comment]
@stsrki So it's more Guid.Comb alike then, but for me it's fine ;)

**Comment by tommarien** [comment]
@stsrki Thanks, very cleanly done

**Pull request merged**
