### PR TITLE
Albacore upgrade

### LINKED ISSUE #555: Upgrade to Albacore 1.0 (equivalent to 0.3.5) or 2.0?
I can assist.

### PR DESCRIPTION
**Pull request by daniellee**
This makes large changes to the packaging script. It adds the files directly to the nuspec files instead of copying them to the packages folder.

Includes a fix to the solution file so that the release configuration sets the correct platform for the FluentMigrator.Console project.

I think I have got everything working although I'm pretty crap at Rake and Ruby so any improvements are welcome! 

However, I need help with one last thing. @haf how do I add the System.CLSCompliantAttribute with the asmver class. And just to double check with @tommarien we are keeping it? The reason given to include it in #447 was "The down-side of not having this is for the library users that need to mark everything which uses given library with [CLSCompliant(false)] attribute."

I haven't added the nuget publish bit yet. But should be simple:

```ruby
Albacore::Tasks::Release.new :release,
                             pkg_dir: 'nuget',
                             depend_on: :create_nuget,
                             nuget_exe: 'tools/NuGet.exe',
                             api_key: ENV['NUGET_KEY']
```

@tommarien do you know how to test a nuget publish?

To test building the three nuget packages (that are outputted to the nuget folder): 

    rake nuget:create_nugets

This pr should close #555.

### CODE REVIEW

**Comment by daniellee** [comment]
Oh, one more thing. You have to upgrade your Albacore gem to 2.0 to test this.

**Comment by tommarien** [comment]
@daniellee What do you mean by testing nuget ?, you mean local file nuget repo or ?

**Comment by haf** [comment]
@daniellee about CLSCompliantAttribute: how about a 'add literal attribute name' method in albacore?

**Comment by haf** [comment]
@daniellee the release task [looks at all files with the right number and push those](https://github.com/Albacore/albacore/blob/master/lib/albacore/tasks/release.rb#L156)

**Comment by daniellee** [comment]
@haf it sort of works with CLSCompliant: true but doesn't build. I'm still missing a Using System; or that the Attribute would be System.CLSCompliant. How can I add that?

```csharp
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: AssemblyVersion("1.4.0.0")]
[assembly: AssemblyFileVersion("1.4.0.0")]
[assembly: AssemblyProduct("FluentMigrator")]
[assembly: AssemblyCopyright("Copyright - Sean Chambers 2008-2015")]
[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: CLSCompliant(true)]
```

**Comment by daniellee** [comment]
@tommarien I was thinking that as you have the API key, that you could test out the publish task next time you want to publish a new Nuget. And therefore it would be better if you got something working locally and then commit the change yourself. I can add the release task but I can't really test it for real.

I am also thinking of doing something more advanced with the release notes part. At the moment, it is just a link to the releases page. I have to a bit of research and figure out how to get the text for the release from Github.

**Comment by haf** [comment]
@daniellee could you please open an issue at albacore for multiple usings?

**Comment by haf** [comment]
https://github.com/Albacore/albacore/issues/151

**Comment by daniellee** [comment]
@haf I didn't manage to open an issue. You had already fixed it! Thanks for all the help. I think we have a working Rake/Albacore script now.

**Comment by haf** [comment]
@daniellee great =)

**Comment by daniellee** [comment]
I tested out the new release notes feature that @haf just added to Albacore. This uses the git log to generate release notes that can be included in the Release Notes field in the nugets. The result would be something like this for the last release:

Release Notes for 1.4.0:

 * Bump version for release
 * Merge pull request #562 of tommarien/oracleAlterDefault
 * Merge pull request #561 of daniellee/sqlserver2014
 * Merge pull request #537 of ericburcham/master
 * Merge pull request #558 of DanCorder/master
 * Revert changes to IntegrationTestOptions
 * Closes #551: Oracle Constraints
 * integration tests run on Sql Server 2014 too
 * Adds stub for Sql Server 2014 support
 * Update README.textile
 * Updated TimestampedMigrationAttribute to use the format yyyyMMddhhmmss.
 * Merge remote-tracking branch 'upstream/master'
 * Potential fix for #398
 * Added forward only migration resharper template
 * Deleted Settings.StyleCop.Old
 * Removed Settings.SyleCop file.
 * Merge branch 'master' of https://github.com/ericburcham/fluentmigrator
 * Added TimestampedMigrationAttribute including code coverage.
 * Added TimestampedMigrationAttribute including code coverage.

What do you think @tommarien ?

**Comment by tommarien** [comment]
@daniellee it's not bad but it needs cleaning. Last release i used gitreleasenotes to generate md and,cleaned output. When i upload the packages i just copy our release notes to each of them.

**Comment by haf** [comment]
You can set `release_notes` in the rakefile and it'll override the defaults.

**Comment by tommarien** [comment]
@daniellee and @haf thanks for this. I only needed to update the gemfile.lock. Seems to build nugets fine ;)

**Pull request merged**
